[2023-09-04 10:43:37,713]160numexpr.utils-INFO-NumExpr defaulting to 6 threads.
[2023-09-04 10:43:43,004]361flask_cors.core-WARNING-Unknown option passed to Flask-CORS: support_credentials
[2023-09-04 10:43:43,004]361flask_cors.core-WARNING-Unknown option passed to Flask-CORS: support_credentials
[2023-09-04 10:43:49,108]16chromadb.telemetry.posthog-INFO-Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
[2023-09-04 10:43:52,586]187werkzeug-INFO-[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.2:5000
[2023-09-04 10:43:52,586]187werkzeug-INFO-[33mPress CTRL+C to quit[0m
[2023-09-04 10:49:00,670]126chromadb.segment.impl.vector.local_hnsw-WARNING-Number of requested results 4 is greater than number of elements in index 1, updating n_results = 1
[2023-09-04 10:49:02,073]1414app-ERROR-Exception on /ask [POST]
Traceback (most recent call last):
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Marvel\eds\app.py", line 74, in ask_question
    result = analyze_and_answer(question, vectordb)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Marvel\eds\modules\analysis.py", line 167, in analyze_and_answer
    query =agent.run(qa(user_query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 475, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 259, in __call__
    inputs = self.prep_inputs(inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 413, in prep_inputs
    self._validate_inputs(inputs)
  File "C:\Users\parth.chaturvedi\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 171, in _validate_inputs
    raise ValueError(f"Missing some input keys: {missing_keys}")
ValueError: Missing some input keys: {'input'}
[2023-09-04 10:49:02,120]187werkzeug-INFO-127.0.0.1 - - [04/Sep/2023 10:49:02] "[35m[1mPOST /ask HTTP/1.1[0m" 500 -
[2023-09-04 10:52:01,393]187werkzeug-INFO-127.0.0.1 - - [04/Sep/2023 10:52:01] "[35m[1mPOST /upload HTTP/1.1[0m" 201 -
